// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyxbwqalmbdywmkviecv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5eGJ3cWFsbWJkeXdta3ZpZWN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDIyNzksImV4cCI6MjA2MTQxODI3OX0.D-CqUnCzve4TB0qJihHL9ooTh1VVngFMFvVHwOHCrZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);